apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sshd
  name: sshd
spec:
  containers:
  - name: sshd
    image: ghcr.io/linuxserver/openssh-server
    env:
    - name: PUBLIC_KEY_DIR
      value: /data/.ssh
    - name: USER_NAME
      value: user
    volumeMounts:
    - name: authorized-keys
      mountPath: /data/.ssh 
    - name: sshd-config
      mountPath: /config/ssh_host_keys/sshd_config
      subPath: sshd_config  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: authorized-keys
    configMap:
      name: ssh-keys  
  - name: sshd-config
    configMap:
      name: sshd-config